
-a --all列出所有的檔案，包含以「.」開頭的隱藏檔
-A --almost-all列出所有的檔案，隱藏檔，但不包括「.」與「..」兩個目錄
-C --list entries by colums按行列列舉資料
--color --to distinguish file types藉顏色辨認檔案特性，正常檔案（黑色）；可執行檔（綠色）；連鎖（淺藍色）；目錄（藍色），
-d --directory列出目錄本身，而不列出目錄內的檔案
-F --clasify分類「*」代表可執行檔；「/」代表目錄；「=」代表socket檔「|」代表FIFO檔
-h --human-readable檔案大小單位，以容易閱讀的方式顯示
-i --inode索引節點
-l --use a long listing format以長格式表示，包含檔案屬性。
-r --reverse英文字母由大向小排序
-R --recursive遞迴地列出目錄樹下的所有內容
-s --size檔案大小
-S --sort by file size依佔用空間大小掛序
-t --time依照檔案的修改時間排序
